const APP_NAME = "CityPulse AI";

function clean(value, fallback = "Not available") {
  if (value === null || value === undefined || value === "") return fallback;
  return String(value);
}

export function buildReportShareText(report = {}) {
  const id = clean(report.reportId || report.id, "CITYPULSE");
  const title = clean(report.title || report.issueTitle, "Civic Issue");
  const category = clean(report.category);
  const priority = clean(report.priority || report.severity);
  const status = clean(report.status, "Submitted");
  const location = clean(
    report.location?.address ||
    report.address ||
    report.location?.name ||
    report.location
  );

  const description = clean(
    report.description ||
    report.issueDescription ||
    report.aiSummary,
    "No description provided"
  );

  const department = clean(
    report.department ||
    report.assignedDepartment,
    "Civic Department"
  );

  const createdAt = report.createdAt
    ? new Date(report.createdAt).toLocaleString()
    : new Date().toLocaleString();

  return [
    `🏙️ ${APP_NAME} — Civic Issue Report`,
    ``,
    `📋 Report ID: ${id}`,
    `⚠️ Issue: ${title}`,
    `🏷️ Category: ${category}`,
    `🚨 Priority: ${priority}`,
    `📌 Status: ${status}`,
    `🏢 Department: ${department}`,
    `📍 Location: ${location}`,
    ``,
    `📝 Description:`,
    description,
    ``,
    `🕒 Reported: ${createdAt}`,
    ``,
    `Generated by ${APP_NAME}`
  ].join("\n");
}

export function buildEmailSubject(report = {}) {
  const id = report.reportId || report.id || "CITYPULSE";
  const title = report.title || report.issueTitle || "Civic Issue";
  return `[${APP_NAME}] ${title} — ${id}`;
}

export function getWhatsAppUrl(report = {}) {
  const text = encodeURIComponent(buildReportShareText(report));
  return `https://wa.me/?text=${text}`;
}

export function getEmailUrl(report = {}, recipient = "") {
  const subject = encodeURIComponent(buildEmailSubject(report));
  const body = encodeURIComponent(buildReportShareText(report));

  const safeRecipient = recipient
    ? encodeURIComponent(recipient)
    : "";

  return `mailto:${safeRecipient}?subject=${subject}&body=${body}`;
}

export async function copyReportShareText(report = {}) {
  const text = buildReportShareText(report);

  if (navigator?.clipboard?.writeText) {
    await navigator.clipboard.writeText(text);
    return true;
  }

  const textarea = document.createElement("textarea");
  textarea.value = text;
  textarea.style.position = "fixed";
  textarea.style.opacity = "0";
  document.body.appendChild(textarea);
  textarea.select();

  const copied = document.execCommand("copy");
  textarea.remove();

  return copied;
}

export function nativeShareAvailable() {
  return typeof navigator !== "undefined" &&
    typeof navigator.share === "function";
}

export async function nativeShareReport(report = {}) {
  if (!nativeShareAvailable()) return false;

  await navigator.share({
    title: buildEmailSubject(report),
    text: buildReportShareText(report)
  });

  return true;
}

export const shareService = {
  buildReportShareText,
  buildEmailSubject,
  getWhatsAppUrl,
  getEmailUrl,
  copyReportShareText,
  nativeShareAvailable,
  nativeShareReport
};
