function safe(value, fallback = "Not provided") {
  if (
    value === undefined ||
    value === null ||
    String(value).trim() === ""
  ) {
    return fallback;
  }

  return String(value);
}

export function buildBackendShareText(
  report = {}
) {
  const ai =
    report.aiAnalysis || {};

  const location =
    report.location || {};

  const observations =
    Array.isArray(
      ai.observations
    )
      ? ai.observations
          .map(
            (item) =>
              `• ${safe(item)}`
          )
          .join("\n")
      : "• None provided";

  const hasCoordinates =
    Number.isFinite(
      location.latitude
    ) &&
    Number.isFinite(
      location.longitude
    );

  const mapUrl =
    hasCoordinates
      ? `https://www.openstreetmap.org/?mlat=${location.latitude}&mlon=${location.longitude}#map=18/${location.latitude}/${location.longitude}`
      : "";

  return [
    "CITYPULSE AI — CIVIC ISSUE REPORT",
    "",
    `Report ID: ${safe(
      report.reportId
    )}`,
    `Status: ${safe(
      report.status,
      "Submitted"
    )}`,
    `Category: ${safe(
      report.category ||
        report.issueType
    )}`,
    `Severity: ${safe(
      report.severity
    )}/5`,
    `Priority: ${safe(
      report.priority
    )}`,
    "",
    "DESCRIPTION",
    safe(
      report.description
    ),
    "",
    "LOCATION",
    `Address: ${safe(
      location.address
    )}`,
    hasCoordinates
      ? `Coordinates: ${location.latitude}, ${location.longitude}`
      : "Coordinates unavailable",
    mapUrl
      ? `Map: ${mapUrl}`
      : "",
    "",
    "AI ASSESSMENT",
    `Detected issue: ${safe(
      ai.detectedIssue
    )}`,
    `Confidence: ${safe(
      ai.confidence,
      "0"
    )}%`,
    `Department: ${safe(
      ai.department
    )}`,
    "",
    "OBSERVATIONS",
    observations,
    "",
    "RECOMMENDATION",
    safe(
      ai.recommendation
    ),
    "",
    "Generated by CityPulse AI"
  ]
    .filter(
      (line) => line !== ""
    )
    .join("\n");
}
